package G45_Lexicon.view;

public enum MenuOption {
    QUIT,
    ADD_TASK,
    ADD_PERSON,
    DELETE_PERSON_BY_PERSON_ID,
    DELETE_TASK_BY_TASK_ID,
    UPDATE_PERSON_BY_PERSON_ID,
    UPDATE_TASK_BY_TASK_ID,
    DISPLAY_ALL_TASKS,
    DISPLAY_ALL_PEOPLE,
    FIND_TASKS_BY_PERSON_ID,
    FIND_TASKS_BY_TASK_ID,
    FIND_TASKS_BY_USERNAME,
    FIND_TASKS_BY_ROLE,
    FIND_TASKS_BY_DONE_STATUS,
    FIND_TASKS_BY_TITLE,
}
